create table "public"."alerts" (
    "improvement_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "account_id" bigint,
    "title" text,
    "alert_date" timestamp without time zone,
    "alert_status" character varying
);


alter table "public"."alerts" enable row level security;

create table "public"."campaigns" (
    "campaign_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "account_id" bigint,
    "campaign_name" character varying,
    "campaign_status" character varying,
    "campaign_daily_budget" numeric,
    "campaign_start_date" timestamp without time zone
);


alter table "public"."campaigns" enable row level security;

create table "public"."google_ads_accounts" (
    "account_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "account_number" character varying,
    "account_name" text
);


alter table "public"."google_ads_accounts" enable row level security;

create table "public"."user_accessible_accounts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "account_id" bigint
);


alter table "public"."user_accessible_accounts" enable row level security;

create table "public"."user_profiles" (
    "user_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "avatar_url" text,
    "email" text,
    "oauth_token" text,
    "color" character varying,
    "updated_at" timestamp with time zone default now()
);


alter table "public"."user_profiles" enable row level security;

CREATE UNIQUE INDEX alerts_pkey ON public.alerts USING btree (improvement_id);

CREATE UNIQUE INDEX campaign_id_pkey ON public.campaigns USING btree (campaign_id);

CREATE UNIQUE INDEX google_ads_accounts_account_id_key ON public.google_ads_accounts USING btree (account_id);

CREATE UNIQUE INDEX google_ads_accounts_pkey ON public.google_ads_accounts USING btree (account_id);

CREATE UNIQUE INDEX user_accessible_accounts_pkey ON public.user_accessible_accounts USING btree (id);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (user_id);

CREATE UNIQUE INDEX user_profiles_user_id_key ON public.user_profiles USING btree (user_id);

alter table "public"."alerts" add constraint "alerts_pkey" PRIMARY KEY using index "alerts_pkey";

alter table "public"."campaigns" add constraint "campaign_id_pkey" PRIMARY KEY using index "campaign_id_pkey";

alter table "public"."google_ads_accounts" add constraint "google_ads_accounts_pkey" PRIMARY KEY using index "google_ads_accounts_pkey";

alter table "public"."user_accessible_accounts" add constraint "user_accessible_accounts_pkey" PRIMARY KEY using index "user_accessible_accounts_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."alerts" add constraint "alerts_account_id_fkey" FOREIGN KEY (account_id) REFERENCES google_ads_accounts(account_id) not valid;

alter table "public"."alerts" validate constraint "alerts_account_id_fkey";

alter table "public"."campaigns" add constraint "campaigns_account_id_fkey" FOREIGN KEY (account_id) REFERENCES google_ads_accounts(account_id) not valid;

alter table "public"."campaigns" validate constraint "campaigns_account_id_fkey";

alter table "public"."google_ads_accounts" add constraint "google_ads_accounts_account_id_key" UNIQUE using index "google_ads_accounts_account_id_key";

alter table "public"."user_accessible_accounts" add constraint "user_accessible_accounts_account_id_fkey" FOREIGN KEY (account_id) REFERENCES google_ads_accounts(account_id) not valid;

alter table "public"."user_accessible_accounts" validate constraint "user_accessible_accounts_account_id_fkey";

alter table "public"."user_accessible_accounts" add constraint "user_accessible_accounts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) not valid;

alter table "public"."user_accessible_accounts" validate constraint "user_accessible_accounts_user_id_fkey";

alter table "public"."user_profiles" add constraint "user_profiles_user_id_key" UNIQUE using index "user_profiles_user_id_key";

grant delete on table "public"."alerts" to "anon";

grant insert on table "public"."alerts" to "anon";

grant references on table "public"."alerts" to "anon";

grant select on table "public"."alerts" to "anon";

grant trigger on table "public"."alerts" to "anon";

grant truncate on table "public"."alerts" to "anon";

grant update on table "public"."alerts" to "anon";

grant delete on table "public"."alerts" to "authenticated";

grant insert on table "public"."alerts" to "authenticated";

grant references on table "public"."alerts" to "authenticated";

grant select on table "public"."alerts" to "authenticated";

grant trigger on table "public"."alerts" to "authenticated";

grant truncate on table "public"."alerts" to "authenticated";

grant update on table "public"."alerts" to "authenticated";

grant delete on table "public"."alerts" to "service_role";

grant insert on table "public"."alerts" to "service_role";

grant references on table "public"."alerts" to "service_role";

grant select on table "public"."alerts" to "service_role";

grant trigger on table "public"."alerts" to "service_role";

grant truncate on table "public"."alerts" to "service_role";

grant update on table "public"."alerts" to "service_role";

grant delete on table "public"."campaigns" to "anon";

grant insert on table "public"."campaigns" to "anon";

grant references on table "public"."campaigns" to "anon";

grant select on table "public"."campaigns" to "anon";

grant trigger on table "public"."campaigns" to "anon";

grant truncate on table "public"."campaigns" to "anon";

grant update on table "public"."campaigns" to "anon";

grant delete on table "public"."campaigns" to "authenticated";

grant insert on table "public"."campaigns" to "authenticated";

grant references on table "public"."campaigns" to "authenticated";

grant select on table "public"."campaigns" to "authenticated";

grant trigger on table "public"."campaigns" to "authenticated";

grant truncate on table "public"."campaigns" to "authenticated";

grant update on table "public"."campaigns" to "authenticated";

grant delete on table "public"."campaigns" to "service_role";

grant insert on table "public"."campaigns" to "service_role";

grant references on table "public"."campaigns" to "service_role";

grant select on table "public"."campaigns" to "service_role";

grant trigger on table "public"."campaigns" to "service_role";

grant truncate on table "public"."campaigns" to "service_role";

grant update on table "public"."campaigns" to "service_role";

grant delete on table "public"."google_ads_accounts" to "anon";

grant insert on table "public"."google_ads_accounts" to "anon";

grant references on table "public"."google_ads_accounts" to "anon";

grant select on table "public"."google_ads_accounts" to "anon";

grant trigger on table "public"."google_ads_accounts" to "anon";

grant truncate on table "public"."google_ads_accounts" to "anon";

grant update on table "public"."google_ads_accounts" to "anon";

grant delete on table "public"."google_ads_accounts" to "authenticated";

grant insert on table "public"."google_ads_accounts" to "authenticated";

grant references on table "public"."google_ads_accounts" to "authenticated";

grant select on table "public"."google_ads_accounts" to "authenticated";

grant trigger on table "public"."google_ads_accounts" to "authenticated";

grant truncate on table "public"."google_ads_accounts" to "authenticated";

grant update on table "public"."google_ads_accounts" to "authenticated";

grant delete on table "public"."google_ads_accounts" to "service_role";

grant insert on table "public"."google_ads_accounts" to "service_role";

grant references on table "public"."google_ads_accounts" to "service_role";

grant select on table "public"."google_ads_accounts" to "service_role";

grant trigger on table "public"."google_ads_accounts" to "service_role";

grant truncate on table "public"."google_ads_accounts" to "service_role";

grant update on table "public"."google_ads_accounts" to "service_role";

grant delete on table "public"."user_accessible_accounts" to "anon";

grant insert on table "public"."user_accessible_accounts" to "anon";

grant references on table "public"."user_accessible_accounts" to "anon";

grant select on table "public"."user_accessible_accounts" to "anon";

grant trigger on table "public"."user_accessible_accounts" to "anon";

grant truncate on table "public"."user_accessible_accounts" to "anon";

grant update on table "public"."user_accessible_accounts" to "anon";

grant delete on table "public"."user_accessible_accounts" to "authenticated";

grant insert on table "public"."user_accessible_accounts" to "authenticated";

grant references on table "public"."user_accessible_accounts" to "authenticated";

grant select on table "public"."user_accessible_accounts" to "authenticated";

grant trigger on table "public"."user_accessible_accounts" to "authenticated";

grant truncate on table "public"."user_accessible_accounts" to "authenticated";

grant update on table "public"."user_accessible_accounts" to "authenticated";

grant delete on table "public"."user_accessible_accounts" to "service_role";

grant insert on table "public"."user_accessible_accounts" to "service_role";

grant references on table "public"."user_accessible_accounts" to "service_role";

grant select on table "public"."user_accessible_accounts" to "service_role";

grant trigger on table "public"."user_accessible_accounts" to "service_role";

grant truncate on table "public"."user_accessible_accounts" to "service_role";

grant update on table "public"."user_accessible_accounts" to "service_role";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";


